CXX = g++

# 1. Removed -flto from here
CXXFLAGS = -std=c++11 -I. -I./imgui -I./imgui/backends -Os -DNDEBUG

# 2. Removed -flto from here, but KEEP -s
LDFLAGS = -s

LIBS = -lglfw3 -lopengl32 -lgdi32

SRCS = main.cpp \
       $(wildcard imgui/*.cpp) \
       imgui/backends/imgui_impl_glfw.cpp \
       imgui/backends/imgui_impl_opengl3.cpp

TARGET = main 
# aahhh comments on  work in new lines
# anywy add -mwindows for no console
all:
	$(CXX) $(CXXFLAGS) $(SRCS) $(LDFLAGS) $(LIBS) -o $(TARGET) 

clean:
	rm -f $(TARGET).exe
